apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-dep
    chapter: first-app #自己加的
  name: nginx-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-dep
  strategy: {}
  template: #pod 模板
    metadata:
      labels:
        app: nginx-dep
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort:  80
        resources: {}

